version: '3'

services:
  wp-bot:
    build: .
    container_name: wp-bot
    volumes:
      - .:/usr/src/app
    environment:
      - http_proxy=http://proxy-server:port
      - https_proxy=http://proxy-server:port
      - NODE_ENV=production
    ports:
      - "3000:3000"  # Eğer dış dünyadan erişmek istiyorsanız port açabilirsiniz.
    restart: always
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
